version: "3.3"
services:
  database1:
    image: wnameless/oracle-xe-11g-r2
    environment:
      ORACLE_ALLOW_REMOTE: 'true'
      GLOBAL_NAMES: 'true'
  database2:
    image: wnameless/oracle-xe-11g-r2
    environment:
      ORACLE_ALLOW_REMOTE: 'true'
      GLOBAL_NAMES: 'true'
  database3:
    image: wnameless/oracle-xe-11g-r2
    environment:
      ORACLE_ALLOW_REMOTE: 'true'
      GLOBAL_NAMES: 'true'
  database_main:
    build: .
    ports:
      - 49164:1521
      - 8080:8080
    environment:
      ORACLE_ALLOW_REMOTE: 'true'
      GLOBAL_NAMES: 'true'