version: "3.3"
services:
  database1:
    depends_on:
      - database_main    
    build: ./database1/
    environment:
      ORACLE_ALLOW_REMOTE: 'true'
      GLOBAL_NAMES: 'true'
    ports:
      - 49165:1521
  database2:
    build: ./database2/
    environment:
      ORACLE_ALLOW_REMOTE: 'true'
      GLOBAL_NAMES: 'true'
    ports:
      - 49166:1521
  database3:
    build: ./database3/
    environment:
      ORACLE_ALLOW_REMOTE: 'true'
      GLOBAL_NAMES: 'true'
    ports:
      - 49167:1521
  database_main:
#     depends_on:
#      - database1
#      - database2
#      - database3
    build: .
    ports:
      - 49164:1521
      - 8080:8080
    environment:
      ORACLE_ALLOW_REMOTE: 'true'
      GLOBAL_NAMES: 'true'